(function(root){
'use strict';
const E=root.PixelEngine;
function createRenderer(screen,source){
const ctx=screen.getContext('2d'),sctx=source.getContext('2d'),noise=document.createElement('canvas'),nctx=noise.getContext('2d');
let noiseKey='',noiseFrame=-1;const photos={};
function preload(name,path){const img=new Image();img.decoding='async';img.onload=()=>{photos[name]=img;window.dispatchEvent(new Event('pixelphotoready'));};img.onerror=()=>{photos[name]=null;window.dispatchEvent(new Event('pixelphotoerror'));};img.src=path;}
for(const name of new Set(E.levels.filter(c=>c.photo).map(c=>c.photo)))preload(name,'assets/'+name+'.jpg');
function noiseTile(fine,frame){const key=fine?'fine':'coarse';if(noiseKey===key&&noiseFrame===frame)return;noiseKey=key;noiseFrame=frame;noise.width=fine?480:240;noise.height=fine?270:135;const data=nctx.createImageData(noise.width,noise.height),rng=E.random(1729+frame*7919);for(let p=0;p<data.data.length;p+=4){const v=110+Math.floor(rng()*55);data.data[p]=v-6;data.data[p+1]=v;data.data[p+2]=v+12;data.data[p+3]=255;}nctx.putImageData(data,0,0);}
function drawNoise(t,fine,overlay=false){noiseTile(fine,Math.floor(t*7));ctx.save();ctx.imageSmoothingEnabled=false;if(overlay)ctx.globalAlpha=.13;ctx.drawImage(noise,0,0,E.W,E.H);ctx.restore();}
function photoBackground(c,t){const img=photos[c.photo];ctx.fillStyle='#808080';ctx.fillRect(0,0,E.W,E.H);if(!img)return false;const zoom=c.motion?1.08+.24*(.5-.5*Math.cos(t*.22)):1.08,scale=Math.max(E.W/img.naturalWidth,E.H/img.naturalHeight)*zoom,w=img.naturalWidth*scale,h=img.naturalHeight*scale,dx=(E.W-w)/2+(c.motion?Math.sin(t*.13)*(w-E.W)*.22:0),dy=(E.H-h)/2+(c.motion?Math.sin(t*.11)*(h-E.H)*.18:0);ctx.save();ctx.globalAlpha=.5;ctx.drawImage(img,dx,dy,w,h);ctx.restore();return true;}
function background(c,t){ctx.fillStyle=c.bg;ctx.fillRect(0,0,E.W,E.H);if(c.pattern==='gradient'){const g=ctx.createLinearGradient(0,0,E.W,E.H);g.addColorStop(0,c.bg);g.addColorStop(1,c.bg==='#6a88df'?'#c2b5dd':'#536780');ctx.fillStyle=g;ctx.fillRect(0,0,E.W,E.H);}else if(c.pattern==='stripes'){ctx.fillStyle='rgba(255,255,255,.065)';for(let x=0;x<E.W;x+=32)ctx.fillRect(x,0,16,E.H);}else if(c.pattern==='noise'||c.pattern==='fine-noise'){drawNoise(t,c.pattern==='fine-noise');}else if(c.pattern==='drift'){const shift=(t*15)%56;for(let x=-56;x<E.W+56;x+=56){ctx.fillStyle='#a2b2cc';ctx.fillRect(x+shift,0,25,E.H);}}else if(c.pattern==='waves'){const g=ctx.createLinearGradient(E.W*(.2+.15*Math.sin(t*.2)),0,E.W,E.H);g.addColorStop(0,'#7387b0');g.addColorStop(.4+.12*Math.sin(t*.24),'#adb7cb');g.addColorStop(1,'#78889f');ctx.fillStyle=g;ctx.fillRect(0,0,E.W,E.H);for(let y=-24;y<E.H+24;y+=25){ctx.beginPath();for(let x=0;x<=E.W;x+=12){const py=y+Math.sin(x*.013+t*.55)*14;x===0?ctx.moveTo(x,py):ctx.lineTo(x,py);}ctx.strokeStyle='rgba(35,55,86,.2)';ctx.lineWidth=2;ctx.stroke();}}else if(c.pattern==='grid'){const offset=(t*10)%36;for(let y=-36;y<E.H+36;y+=36)for(let x=-36;x<E.W+36;x+=36){const v=Math.round(114+30*Math.sin(x*.012+y*.017+t*.5));ctx.fillStyle='rgb('+v+','+(v+10)+','+(v+24)+')';ctx.fillRect(x+offset,y+offset,34,34);}}else if(c.pattern==='photo'||c.pattern==='photo-noise'){const ready=photoBackground(c,t);if(!ready){drawNoise(t,true);if(photos[c.photo]===null)return'fallback';return'loading';}if(c.pattern==='photo-noise')drawNoise(t,true,true);}return'ready';}
function render(stage,t){const state=background(stage.cfg,t);sctx.clearRect(0,0,E.W,E.H);sctx.drawImage(screen,0,0);const minSize=E.W/Math.max(1,screen.getBoundingClientRect().width);for(const dot of stage.targets){if(dot.found)continue;if(stage.cfg.adaptive&&!dot.color&&state!=='loading'){const p=sctx.getImageData(dot.x,dot.y,1,1).data;dot.color=E.contrastColor(p[0],p[1],p[2]);}const color=dot.color||stage.cfg.color||'#f4f6ff';sctx.fillStyle=color;sctx.fillRect(dot.x,dot.y,dot.size,dot.size);ctx.fillStyle=color;const size=Math.max(dot.size,minSize);ctx.fillRect(dot.x+dot.size/2-size/2,dot.y+dot.size/2-size/2,size,size);}return state;}
return{render};
}
root.PixelRenderer={createRenderer};
})(window);
